//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace xk3yScanner.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool menuRename {
            get {
                return ((bool)(this["menuRename"]));
            }
            set {
                this["menuRename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool menuPrefer3DCovers {
            get {
                return ((bool)(this["menuPrefer3DCovers"]));
            }
            set {
                this["menuPrefer3DCovers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point formLocation {
            get {
                return ((global::System.Drawing.Point)(this["formLocation"]));
            }
            set {
                this["formLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("912, 547")]
        public global::System.Drawing.Size formSize {
            get {
                return ((global::System.Drawing.Size)(this["formSize"]));
            }
            set {
                this["formSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gamePath {
            get {
                return ((string)(this["gamePath"]));
            }
            set {
                this["gamePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://youtube.googleapis.com/v/{video}&hl=sv")]
        public string youtubeUrl {
            get {
                return ((string)(this["youtubeUrl"]));
            }
            set {
                this["youtubeUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://marketplace.xbox.com/{place}/Product/66acd000-77fe-1000-9115-d802{titleid}" +
            "?nosplash=1")]
        public string xboxUri {
            get {
                return ((string)(this["xboxUri"]));
            }
            set {
                this["xboxUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<div class=\""Text\"">.*?<p>(?<summary>.*?)</p>.*?class=\""grid-6\"".*?<img alt=\""(?<title>.*?)\""*.?class=\""boxart\"".*?src=\""(?<coverurl>.*?)\""(.*?(Developer:|開発元:)</label>(?<developer>.*?)</li>.*?|.*?)(Publisher:|発売元:)</label>(?<publisher>.*?)</li>.*?(Genre:|ジャンル:)</label>(?<genre>.*?)</li>")]
        public string xboxRegex {
            get {
                return ((string)(this["xboxRegex"]));
            }
            set {
                this["xboxRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://spiffycovers.com/covers/view/360/{titleid}/")]
        public string spiffyUri {
            get {
                return ((string)(this["spiffyUri"]));
            }
            set {
                this["spiffyUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("class=\"cover_downloads_title\">(.*?)</h2>.*?class=\"cover_downloads_3d\">.*?<a href=" +
            "\"(.*?)>.*?class=\"cover_downloads_front\">.*?<a href=\"(.*?)>")]
        public string spiffyRegex {
            get {
                return ((string)(this["spiffyRegex"]));
            }
            set {
                this["spiffyRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://spiffycovers.com/cover/{titleid}/360/3D/")]
        public string spiffy3DCover {
            get {
                return ((string)(this["spiffy3DCover"]));
            }
            set {
                this["spiffy3DCover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://spiffycovers.com/cover/{titleid}/360/front/")]
        public string spiffyFrontCover {
            get {
                return ((string)(this["spiffyFrontCover"]));
            }
            set {
                this["spiffyFrontCover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://download.xbox.com/content/images/66acd000-77fe-1000-9115-d802{titleid}/103" +
            "3/boxartlg.jpg")]
        public string xboxCover {
            get {
                return ((string)(this["xboxCover"]));
            }
            set {
                this["xboxCover"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://download.xbox.com/content/images/66acd000-77fe-1000-9115-d802{titleid}/103" +
            "3/banner.png")]
        public string xboxBanner {
            get {
                return ((string)(this["xboxBanner"]));
            }
            set {
                this["xboxBanner"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gdata.youtube.com/feeds/api/videos?category=XBOX360|360&genre=24&q={title}" +
            "+Trailer")]
        public string youtubeUri {
            get {
                return ((string)(this["youtubeUri"]));
            }
            set {
                this["youtubeUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<id>http://gdata.youtube.com/feeds/api/videos/(.*?)</id>.*?<title.*?>(.*?)</title" +
            ">.*?<author>.*?<name>(.*?)</name>")]
        public string youtubeRegex {
            get {
                return ((string)(this["youtubeRegex"]));
            }
            set {
                this["youtubeRegex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.youtube.com/v/{video}")]
        public string youtubeviewurl {
            get {
                return ((string)(this["youtubeviewurl"]));
            }
            set {
                this["youtubeviewurl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://abgx360.net/Apps/Stealth360/GameNameLookup.csv")]
        public string abgxNameLookUpUrl {
            get {
                return ((string)(this["abgxNameLookUpUrl"]));
            }
            set {
                this["abgxNameLookUpUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string abgxGameNameLookup {
            get {
                return ((string)(this["abgxGameNameLookup"]));
            }
            set {
                this["abgxGameNameLookup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string abgxGameNameLookupETAG {
            get {
                return ((string)(this["abgxGameNameLookupETAG"]));
            }
            set {
                this["abgxGameNameLookupETAG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point editLocation {
            get {
                return ((global::System.Drawing.Point)(this["editLocation"]));
            }
            set {
                this["editLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("912, 517")]
        public global::System.Drawing.Size editSize {
            get {
                return ((global::System.Drawing.Size)(this["editSize"]));
            }
            set {
                this["editSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gfxPath {
            get {
                return ((string)(this["gfxPath"]));
            }
            set {
                this["gfxPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkGenre {
            get {
                return ((bool)(this["chkGenre"]));
            }
            set {
                this["chkGenre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkTrailer {
            get {
                return ((bool)(this["chkTrailer"]));
            }
            set {
                this["chkTrailer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkPublisher {
            get {
                return ((bool)(this["chkPublisher"]));
            }
            set {
                this["chkPublisher"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkDeveloper {
            get {
                return ((bool)(this["chkDeveloper"]));
            }
            set {
                this["chkDeveloper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkDiscs {
            get {
                return ((bool)(this["chkDiscs"]));
            }
            set {
                this["chkDiscs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkGameType {
            get {
                return ((bool)(this["chkGameType"]));
            }
            set {
                this["chkGameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkGameDate {
            get {
                return ((bool)(this["chkGameDate"]));
            }
            set {
                this["chkGameDate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkAbgxInfo {
            get {
                return ((bool)(this["chkAbgxInfo"]));
            }
            set {
                this["chkAbgxInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ActiveFolder {
            get {
                return ((string)(this["ActiveFolder"]));
            }
            set {
                this["ActiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InActiveFolder {
            get {
                return ((string)(this["InActiveFolder"]));
            }
            set {
                this["InActiveFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-t --af3 --max -- \"{0}\"")]
        public string AbgxArguments {
            get {
                return ((string)(this["AbgxArguments"]));
            }
            set {
                this["AbgxArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InActiveFolders {
            get {
                return ((bool)(this["InActiveFolders"]));
            }
            set {
                this["InActiveFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FolderStructure {
            get {
                return ((int)(this["FolderStructure"]));
            }
            set {
                this["FolderStructure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>アクション</string>
  <string>Action</string>
  <string>アドベンチャー</string>
  <string>Adventure</string>
  <string>シューティング</string>
  <string>Shooter</string>
  <string>ファミリー</string>
  <string>Family</string>
  <string>格闘</string>
  <string>Fighting</string>
  <string>スポーツ</string>
  <string>Sports</string>
  <string>レクリエーション</string>
  <string>Recreation</string>
  <string>アバター</string>
  <string>Avatar</string>
  <string>戦略</string>
  <string>Strategy</string>
  <string>シミュレーション</string>
  <string>Simulation</string>
  <string>RPG</string>
  <string>Role Playing</string>
  <string>レース</string>
  <string>Racing</string>
  <string>フライト</string>
  <string>Flying</string>
  <string>パズル</string>
  <string>Puzzle</string>
  <string>雑学クイズ</string>
  <string>Trivia</string>
  <string>キャラクター アクション</string>
  <string>Platformer</string>
  <string>その他</string>
  <string>Other</string>
  <string>音楽</string>
  <string>Music</string>
  <string>エデュテイメント</string>
  <string>Educational</string>
  <string>テーブル ゲーム</string>
  <string>Card &amp; Board</string>
  <string />
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection GenreTranslation {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["GenreTranslation"]));
            }
            set {
                this["GenreTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultRegion {
            get {
                return ((int)(this["DefaultRegion"]));
            }
            set {
                this["DefaultRegion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkRegionCode {
            get {
                return ((bool)(this["chkRegionCode"]));
            }
            set {
                this["chkRegionCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string csvItems {
            get {
                return ((string)(this["csvItems"]));
            }
            set {
                this["csvItems"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Argentina|es-AR</string>\r\n  <string>Australia|en-AU</string>\r\n  <string>Be" +
            "lgië|nl-BE</string>\r\n  <string>Belgique|fr-BE</string>\r\n  <string>Brasil|pt-BR</" +
            "string>\r\n  <string>Canada (English)|en-CA</string>\r\n  <string>Canada (Français)|" +
            "fr-CA</string>\r\n  <string>Česká republika|cs-CZ</string>\r\n  <string>Chile|es-CL<" +
            "/string>\r\n  <string>Colombia|es-CO</string>\r\n  <string>Danmark|da-DK</string>\r\n " +
            " <string>Deutschland|de-DE</string>\r\n  <string>España|es-ES</string>\r\n  <string>" +
            "Ελλάδα|el-GR</string>\r\n  <string>France|fr-FR</string>\r\n  <string>Hong Kong S.A." +
            "R. (香港)|zh-HK</string>\r\n  <string>Hong Kong S.A.R. (English)|en-HK</string>\r\n  <" +
            "string>India|en-IN</string>\r\n  <string>Ireland|en-IE</string>\r\n  <string>Israel|" +
            "he-IL</string>\r\n  <string>Italia|it-IT</string>\r\n  <string>日本 (Japan)ja-JP|</str" +
            "ing>\r\n  <string>대한민국 (Korea)|ko-KR</string>\r\n  <string>Magyarország|hu-HU</strin" +
            "g>\r\n  <string>México|es-MX</string>\r\n  <string>Nederland|nl-NL</string>\r\n  <stri" +
            "ng>New Zealand|en-NZ</string>\r\n  <string>Norge|nb-NO</string>\r\n  <string>Österre" +
            "ich|de-AT</string>\r\n  <string>Polska|pl-PL</string>\r\n  <string>Portugal|pt-PT</s" +
            "tring>\r\n  <string>Pоссия|ru-RU</string>\r\n  <string>Saudi Arabia|ar-SA</string>\r\n" +
            "  <string>Schweiz|de-CH</string>\r\n  <string>Singapore|en-SG</string>\r\n  <string>" +
            "Slovakia|sk-SK</string>\r\n  <string>South Africa|en-ZA</string>\r\n  <string>Suisse" +
            "|fr-CH</string>\r\n  <string>Suomi|fi-FI</string>\r\n  <string>Sverige|sv-SE</string" +
            ">\r\n  <string>台灣 (Taiwan)|zh-TW</string>\r\n  <string>Türkiye|tr-TR</string>\r\n  <st" +
            "ring>United Arab Emirates|ar-AE</string>\r\n  <string>United Kingdom|en-GB</string" +
            ">\r\n  <string>United States|en-US</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection xboxStores {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["xboxStores"]));
            }
            set {
                this["xboxStores"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en-US")]
        public string DefaultStore {
            get {
                return ((string)(this["DefaultStore"]));
            }
            set {
                this["DefaultStore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkOverwriteImages {
            get {
                return ((bool)(this["chkOverwriteImages"]));
            }
            set {
                this["chkOverwriteImages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{Title} {OptStrDisc} [{MediaId}][{Regions}]")]
        public string txtTemplate {
            get {
                return ((string)(this["txtTemplate"]));
            }
            set {
                this["txtTemplate"] = value;
            }
        }
    }
}
